# 다운로드

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import shutil
shutil.copytree("/content/drive/MyDrive/final_project/김예지/data/buidling_address_new/","/content/buidling_address_new")

'/content/buidling_address_new'

In [ ]:
shutil.copy2("/content/drive/MyDrive/final_project/김랑하/건축물대장/경기도전체_건축물대장.csv", "/content/")
shutil.copy2("/content/drive/MyDrive/final_project/김랑하/건축물대장/서울전체_건축물대장.csv", "/content/")
shutil.copy2("/content/drive/MyDrive/final_project/김랑하/건축물대장/인천전체_건축물대장.csv", "/content/")

'/content/인천전체_건축물대장.csv'

# 합치기

In [ ]:
import pandas as pd
import glob
import os


csv_files = glob.glob('/content/*대장.csv')

dfs = []

for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

combined_df.to_csv('/content/건축물대장.csv', index=False)

<ipython-input-4-832b626a086c>:11: DtypeWarning: Columns (9,10,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
<ipython-input-4-832b626a086c>:11: DtypeWarning: Columns (9,10,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
<ipython-input-4-832b626a086c>:11: DtypeWarning: Columns (9,10,33,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

In [ ]:
csv_files = glob.glob('/content/buidling_address_new/build*.csv')

dfs = []

for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

combined_df.to_csv('/content/bd.csv', index=False)

In [ ]:
# prompt: adress기준으로 같으면 데이터 중복이므로 삭제

# Assuming the address column is named 'address'
# If it's different, replace 'address' with the actual column name

# Drop duplicates based on the 'address' column, keeping the first occurrence
combined_df = combined_df.drop_duplicates(subset=['address'], keep='first')

# Reset the index after removing duplicates
combined_df = combined_df.reset_index(drop=True)

# Now combined_df contains only unique addresses

# Save the deduplicated DataFrame to a new CSV file
combined_df.to_csv('/content/bd_dup.csv', index=False)

In [ ]:
# Verify the deduplication (optional)
print(f"Original DataFrame shape: {pd.read_csv('/content/bd.csv').shape}")
print(f"Deduplicated DataFrame shape: {combined_df.shape}")

Original DataFrame shape: (151461, 10)
Deduplicated DataFrame shape: (83726, 10)

In [ ]:
factor = ['PK', '시도', '시군구', '법정동', '번', '지', '대지구분',  '건물명', '동명', '대지면적(㎡)',  '주구조', '기타구조', '주용도', '기타용도', '주지붕', '기타지붕', '높이','지상층수',  '허가일', '착공일', '사용승인일']

In [ ]:
# Load the combined CSV file
df = pd.read_csv('/content/건축물대장.csv')

# Drop all other columns
df = df[factor]

# Save the modified DataFrame to a new CSV file
df.to_csv('/content/대장_filtered.csv', index=False)

<ipython-input-9-d7cfc66fdcfa>:2: DtypeWarning: Columns (9,10,33,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/건축물대장.csv')

# 데이터 파악

In [ ]:
dj = pd.read_csv("/content/대장_filtered.csv")
bd = pd.read_csv("/content/bd_dup.csv")

<ipython-input-10-82cd1a4c1f94>:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  dj = pd.read_csv("/content/대장_filtered.csv")

In [ ]:
bd.head(5)

,Unnamed: 0,image_name,id,lat,lon,pixels,road_address,address,building_name,zone_no
0,90000,3437.0,34,37.527316,127.173682,393,경기도 하남시 초광로 75,경기 하남시 광암동 90-2,NaN,12989.0
1,90001,3437.0,35,37.527256,127.175682,375,NaN,경기 하남시 광암동 산 9,NaN,NaN
2,90002,3437.0,36,37.527125,127.171959,2436,NaN,경기 하남시 광암동 405-2,NaN,NaN
3,90003,3437.0,37,37.527180,127.174674,2001,경기도 하남시 초광로 66,경기 하남시 광암동 97-1,NaN,12989.0
4,90004,3437.0,38,37.527093,127.173897,1495,경기도 하남시 초광로 73,경기 하남시 광암동 91,NaN,12989.0

In [ ]:
dj.head(5)

,PK,시도,시군구,법정동,번,지,대지구분,건물명,동명,대지면적(㎡),...,기타구조,주용도,기타용도,주지붕,기타지붕,높이,지상층수,허가일,착공일,사용승인일
0,106112209,인천광역시,서구,서구,0,0,블록,NaN,NaN,235.5,...,철근콘크리트구조,단독주택,단독주택,(철근)콘크리트,평슬라브,12.80,4,20011010,20020319,20020802
1,1000000000000002034513,인천광역시,서구,백석동,0,0,블록,검암역 로열파크씨티 푸르지오 1단지,쓰레기 분리보관소-7,103068.0,...,철근콘크리트구조,공동주택,쓰레기 분리보관소-7,(철근)콘크리트,(철근)콘크리트,2.51,1,20190201,20200519,20230629
2,1000000000000002034517,인천광역시,서구,백석동,0,0,블록,검암역 로열파크씨티 푸르지오 1단지,우수저류조 중간관리층-2,103068.0,...,철근콘크리트구조,공동주택,우수저류조 중간관리층-2,(철근)콘크리트,(철근)콘크리트,0.00,0,20190201,20200519,20230629
3,1000000000000003276357,인천광역시,서구,백석동,0,0,블록,청암주유소,2,0.0,...,강파이프구조,위험물저장및처리시설,위험물저장및처리시설,기타지붕,기타지붕(그라스울판넬),4.80,1,20231113,20231214,20240122
4,1000000000000002031358,인천광역시,서구,백석동,0,0,블록,검암역 로열파크씨티 푸르지오 1단지,106동,0.0,...,철근콘크리트구조,공동주택,공동주택(아파트),(철근)콘크리트,(철근)콘크리트,111.07,39,20190201,20200519,20230629

In [ ]:
# dj의 시도 인덱스 종류 보기

print(dj['시도'].unique())

['인천광역시' '경기도' nan '서울특별시']

In [ ]:
# bd의 address 첫 단어 종류 보기
print(bd['address'].str.split().str[0].unique())

['경기' '인천' '서울' nan]

In [ ]:
#bd의 address중 부천을 포함하는 데이터 5개

# Assuming 'address' column exists in the 'bd' DataFrame
bucheon_addresses = bd[bd['address'].str.contains('부천', na=False)].head(5)
bucheon_addresses

,Unnamed: 0,image_name,id,lat,lon,pixels,road_address,address,building_name,zone_no
527,90732,3450.0,1,37.524556,126.761390,446,경기도 부천시 오정구 오정로 12,경기 부천시 오정구 삼정동 34-8,NaN,14448.0
528,90733,3450.0,2,37.524373,126.761851,10665,NaN,경기 부천시 오정구 삼정동 34-21,NaN,NaN
529,90734,3450.0,3,37.524395,126.763514,27972,NaN,경기 부천시 오정구 삼정동 34-11,NaN,NaN
530,90735,3450.0,4,37.524594,126.765308,385,경기도 부천시 오정구 오정로 50-28,경기 부천시 오정구 삼정동 29-22,NaN,14448.0
531,90737,3450.0,6,37.524589,126.765991,1219,경기도 부천시 오정구 오정로 58,경기 부천시 오정구 삼정동 24-13,NaN,14448.0

In [ ]:
bucheon_addresses = dj[dj['시군구'].str.contains('부천', na=False)].head(5)
bucheon_addresses

,PK,시도,시군구,법정동,번,지,대지구분,건물명,동명,대지면적(㎡),...,기타구조,주용도,기타용도,주지붕,기타지붕,높이,지상층수,허가일,착공일,사용승인일
375733,109711086,경기도,부천시 원미구,원미동,0,0,대지,NaN,NaN,498.3,...,"철근콘크리트조, 조적조",공장,공장,(철근)콘크리트,평스라브,11.0,3,19950225,19950317,19950714
375734,10971857,경기도,부천시 원미구,원미동,1,1,대지,NaN,NaN,425.6,...,조적조,제1종근린생활시설,제1종근린생활시설,(철근)콘크리트,슬라브,4.9,1,19961116,19961118,19970509
375735,10971858,경기도,부천시 원미구,원미동,1,2,대지,NaN,NaN,425.6,...,철근콘크리트조,제2종근린생활시설,"근린생활시설,기술계학원",(철근)콘크리트,콘크리트평슬라브,15.7,5,19910504,19910504,19911210
375736,10971859,경기도,부천시 원미구,원미동,1,3,대지,NaN,NaN,334.2,...,"철근콘크리트조, 조적조",제2종근린생활시설,"근린생활시설, 단독주택",(철근)콘크리트,콘크리트평슬라브,16.6,4,19940412,19940607,19941205
375737,10971860,경기도,부천시 원미구,원미동,1,4,대지,NaN,NaN,124.2,...,조적조,제2종근린생활시설,"단독주택,제1.2종근린생활시설",(철근)콘크리트,슬라브,0.0,3,NaN,NaN,19881217

# 매핑
## 1. 데이터 형태
대장: 시도 시군구 동 따로


---
카카오: 다 하나에 (address)

## 2.시도 표시
대장: ['인천광역시' nan '경기도' '서울특별시']


---


카카오: ['경기' nan '서울' '인천']

## 3. 번지
대장:번 = 본번, 지 = 부번  (본번이 0인 경우 결측, 부번이 0인 경우 부번이 없음)


---


카카오:경기 부천시 오정구 대장동 546-9	본번-부번

## 4. 대장 시군구
대장: 시군구에 분류가 2개인 경우 하나에 있음 예시: 부천시 원미구

In [ ]:
# ====================
# 📦 필수 라이브러리 임포트
# ====================
import pandas as pd
import numpy as np

# ==========================
# 🛠 데이터 전처리 함수 정의
# ==========================
def split_bunji(x):
    """ 안정화된 번지 분할 함수 """
    if pd.isna(x):
        return (pd.NA, pd.NA)
    if '-' in x:
        parts = x.split('-')
        return (int(parts[0]), int(parts[1]))
    elif x.startswith('산'):
        return (int(x[1:]), pd.NA)
    else:
        try:
            return (int(x), pd.NA)
        except:
            return (pd.NA, pd.NA)

def preprocess_bd(bd_df):
    """ BD 데이터 전처리 (오류 수정 버전) """
    df = bd_df.copy()

    # 시도 매핑
    sido_map = {'경기':'경기도', '서울':'서울특별시', '인천':'인천광역시'}
    df['시도'] = df['address'].str.split().str[0].map(sido_map)

    # 주소 분할
    split_addr = df['address'].str.split(n=3, expand=True)
    df['시군구'] = split_addr[1].str.replace('시$', '', regex=True)
    df['법정동'] = split_addr[2].str.replace('동$', '', regex=True)

    # 번지 추출
    bunji = df['address'].str.extract(r'(\d+-\d+|\d+|산\d+)')[0]
    df[['번','지']] = pd.DataFrame(
        bunji.apply(split_bunji).tolist(),
        index=df.index
    )

    # 타입 변환
    return df.astype({'번':'Int64', '지':'Int64'})

def preprocess_dj(dj_df):
    """ DJ 데이터 전처리 (오류 수정 버전) """
    df = dj_df.copy()

    # 법정동 정규화
    df['법정동'] = df['법정동'].str.strip().str.replace('동$', '', regex=True)

    # 번/지 처리
    df['번'] = df['번'].replace(0, pd.NA).astype('Int64')
    df['지'] = df['지'].replace(0, pd.NA).astype('Int64')

    return df


# ====================
# 🧹 데이터 전처리 실행
# ====================
bd_pre = preprocess_bd(bd)
dj_pre = preprocess_dj(dj)

# ====================
# 🤝 데이터 병합 실행
# ====================
merged = pd.merge(
    bd_pre,
    dj_pre,
    on=['시도', '시군구', '법정동', '번', '지'],
    how='inner',
    suffixes=('_bd', '_dj')
)

# ====================
# 🔍 결과 검증
# ====================
def validate_results(df):
    print("="*40)
    print("✅ 데이터 구조 검증")
    print(f"- 컬럼 수: {len(df.columns)}")
    print(f"- 행 수: {len(df)}")

    print("\n✅ NULL 값 검사")
    print(df.isnull().sum())

    print("\n✅ 데이터 타입 검증")
    print(df.dtypes)

    print("\n✅ 샘플 데이터")
    return df.head()

validate_results(merged)

========================================
✅ 데이터 구조 검증
- 컬럼 수: 31
- 행 수: 8758

✅ NULL 값 검사
Unnamed: 0          0
image_name          0
id                  0
lat                 0
lon                 0
pixels              0
road_address     1845
address             0
building_name    3047
zone_no          1845
시도                  0
시군구                 0
법정동                 0
번                   0
지                4084
PK                  0
대지구분                0
건물명              2171
동명               2514
대지면적(㎡)             0
주구조                 0
기타구조               14
주용도                 2
기타용도                7
주지붕                35
기타지붕               79
높이                  0
지상층수                0
허가일               908
착공일              2221
사용승인일             282
dtype: int64

✅ 데이터 타입 검증
Unnamed: 0         int64
image_name       float64
id                 int64
lat              float64
lon              float64
pixels             int64
road_address      object
address           object
building_name     object
zone_no          float64
시도                object
시군구               object
법정동               object
번                  Int64
지                  Int64
PK                object
대지구분              object
건물명               object
동명                object
대지면적(㎡)          float64
주구조               object
기타구조              object
주용도               object
기타용도              object
주지붕               object
기타지붕              object
높이               float64
지상층수               int64
허가일               object
착공일               object
사용승인일             object
dtype: object

✅ 샘플 데이터

,Unnamed: 0,image_name,id,lat,lon,pixels,road_address,address,building_name,zone_no,...,기타구조,주용도,기타용도,주지붕,기타지붕,높이,지상층수,허가일,착공일,사용승인일
0,90448,3445.0,1,37.524298,126.732031,35953,인천광역시 계양구 계양대로16번길 91,인천 계양구 작전동 738-1,NaN,21123.0,...,철골조,공장,"공장,제2종근린생활시설",기타지붕,샌드위치판넬,15.10,3,20000422,20000512,20000819
1,90449,3445.0,2,37.524566,126.734000,3575,인천광역시 계양구 아나지로374번길 11,인천 계양구 작전동 709-7,성우미크론,21128.0,...,일반철골조,제2종근린생활시설,"공장,제1,2종근린생활시설",기타지붕,샌드위치판넬,7.00,2,20010413,20010416,20010627
2,90449,3445.0,2,37.524566,126.734000,3575,인천광역시 계양구 아나지로374번길 11,인천 계양구 작전동 709-7,성우미크론,21128.0,...,"철근콘크리트구조, 세멘부럭조, 철골조",공장,공장,(철근)콘크리트,"스라브, 스레트",0.00,2,19820715,NaN,19821013
3,90449,3445.0,2,37.524566,126.734000,3575,인천광역시 계양구 아나지로374번길 11,인천 계양구 작전동 709-7,성우미크론,21128.0,...,일반철골구조,공장,공장,(철근)콘크리트,평스라브,16.22,4,20030212,20030513,20040917
4,90449,3445.0,2,37.524566,126.734000,3575,인천광역시 계양구 아나지로374번길 11,인천 계양구 작전동 709-7,성우미크론,21128.0,...,세멘부럭조,공장,공장,기타지붕,스라브,0.00,1,NaN,NaN,NaN

In [ ]:
merged.to_csv('/content/merged.csv', index=False)

In [ ]:
# ====================
# 📦 필수 라이브러리 임포트
# ====================
import pandas as pd
import numpy as np

# ==========================
# 🔄 DJ → BD 형식 변환 함수
# ==========================
def transform_dj_to_bd(dj_df):
    """ DJ 데이터를 BD 주소 형식으로 표준화 """
    df = dj_df.copy()

    # 1. 시도명 단축
    sido_map = {
        '경기도': '경기',
        '서울특별시': '서울',
        '인천광역시': '인천'
    }
    df['시도'] = df['시도'].map(sido_map)

    # 2. 법정동 '동' 추가
    df['법정동'] = df['법정동'].apply(
        lambda x: f"{x}동" if not str(x).endswith('동') else x
    )

    # 3. 번지 생성 (산/블록 구분)
    df['번지'] = df.apply(lambda row:
        f"산{row['번']}" if row['대지구분'] == '산' else
        f"{row['번']}-{row['지']}" if pd.notna(row['지']) and row['지'] != 0 else
        f"{row['번']}",
        axis=1
    )

    # 4. 주소 문자열 생성 (BD 형식)
    df['address'] = df['시도'] + ' ' + df['시군구'] + ' ' + df['법정동'] + ' ' + df['번지']

    return df

# ====================
# 🧩 데이터 병합 로직
# ====================
def merge_datasets(bd, dj):
    # 1. 데이터 로드

    # 2. DJ 형식 변환
    dj_transformed = transform_dj_to_bd(dj)

    # 3. 주소 기준 병합
    merged = pd.merge(
        bd,
        dj_transformed,
        on='address',
        how='inner',
        validate='1:m'
    )

    # 4. 성공률 계산
    success_rate = len(merged)/len(bd)
    print(f"▶ 병합 성공률: {success_rate:.1%}")

    return merged

# ====================
# 🔍 검증 리포트 추가
# ====================
def generate_merge_report(merged_df):
    report = {
        'total_records': len(merged_df),
        'missing_pk': merged_df['PK'].isna().sum(),
        'column_details': dict(merged_df.dtypes),
        'sample_data': merged_df.head(3).to_dict('records')
    }
    return report

# ====================
# 🚀 전체 실행 파이프라인
# ====================
if __name__ == "__main__":
    # 데이터 경로 (실제 경로로 변경 필요)
    merged_data = merge_datasets(
      bd,dj
    )

    # 결과 저장
    merged_data.to_csv("merged_final.csv", index=False)
    print("\n✅ 병합 결과 저장 완료")

    # 리포트 생성
    report = generate_merge_report(merged_data)
    print("\n📊 병합 리포트:")
    for key, val in report.items():
        if key != 'sample_data':
            print(f"- {key}: {val}")

▶ 병합 성공률: 76.2%

✅ 병합 결과 저장 완료

📊 병합 리포트:
- total_records: 63834
- missing_pk: 0
- column_details: {'Unnamed: 0': dtype('int64'), 'image_name': dtype('float64'), 'id': dtype('int64'), 'lat': dtype('float64'), 'lon': dtype('float64'), 'pixels': dtype('int64'), 'road_address': dtype('O'), 'address': dtype('O'), 'building_name': dtype('O'), 'zone_no': dtype('float64'), 'PK': dtype('O'), '시도': dtype('O'), '시군구': dtype('O'), '법정동': dtype('O'), '번': dtype('int64'), '지': dtype('int64'), '대지구분': dtype('O'), '건물명': dtype('O'), '동명': dtype('O'), '대지면적(㎡)': dtype('float64'), '주구조': dtype('O'), '기타구조': dtype('O'), '주용도': dtype('O'), '기타용도': dtype('O'), '주지붕': dtype('O'), '기타지붕': dtype('O'), '높이': dtype('float64'), '지상층수': dtype('int64'), '허가일': dtype('O'), '착공일': dtype('O'), '사용승인일': dtype('O'), '번지': dtype('O')}

주요시설과의 거리 고려

In [ ]:
import geopandas as gpd
from shapely.geometry import Point

# CSV A 생성 (과천청사, 팔당댐, 청평댐)
data_a = {
    'name': ['과천정부청사', '팔당댐', '청평댐'],
    'lat': [37.4269905, 37.5254375, 37.7213125],
    'lon': [126.9840938, 127.2784375, 127.4160625]
}

a_gdf = gpd.GeoDataFrame(
    data_a,
    geometry=gpd.points_from_xy(data_a['lon'], data_a['lat']),
    crs='EPSG:4326'
).to_crs('EPSG:32652')  # 한국 UTM 좌표계로 변환

# CSV B 처리
b_gdf = gpd.read_file("/content/merged_final.csv")
b_gdf = gpd.GeoDataFrame(
    b_gdf,
    geometry=gpd.points_from_xy(b_gdf['lon'], b_gdf['lat']),
    crs='EPSG:4326'
).to_crs('EPSG:32652')

# 최종 점수를 저장할 컬럼 초기화
b_gdf['distance_point'] = 0.0

# 각 시설물별로 반복 계산
for _, facility in a_gdf.iterrows():
    # B 데이터와의 거리 계산 (미터 단위)
    distances = b_gdf.geometry.distance(facility.geometry)

    # 3km 이내인 경우 점수 계산
    within_3km = distances <= 3000  # 3km = 3000m
    scores = 3 - (distances[within_3km]/1000)  # km 단위 변환 후 계산

    # 점수 누적
    b_gdf.loc[within_3km, 'distance_point'] += scores

# 결과 저장 (geometry 제외)
b_gdf.drop(columns='geometry').to_csv("final_with_d_score.csv", index=False)

# 그리드 분할

In [ ]:
import numpy as np

# 원본 격자 생성 (68 x 82)
original_grid = np.arange(1, 68 * 82 + 1).reshape(68, 82)

# 그리드 크기 정의
grid_size = 12

# 결과를 저장할 리스트
grids = []
grid_indices = {}
# 상단 그리드
for j in range(0, 82, grid_size):
    grid = original_grid[:grid_size, j:j+grid_size].flatten().tolist()
    grids.append(grid)

# 하단 그리드
for j in range(0, 82, grid_size):
    grid = original_grid[-grid_size:, j:j+grid_size].flatten().tolist()
    grids.append(grid)

# 좌측 그리드 (상단과 하단 제외)
for i in range(grid_size, 68 - grid_size, grid_size):
    grid = original_grid[i:i+grid_size, :grid_size].flatten().tolist()
    grids.append(grid)

# 우측 그리드 (상단과 하단 제외)
for i in range(grid_size, 68 - grid_size, grid_size):
    grid = original_grid[i:i+grid_size, -grid_size:].flatten().tolist()
    grids.append(grid)

# 결과 확인
for i, grid in enumerate(grids):
    print(f"그리드{i+1}: {grid}")

print(f"총 그리드 수: {len(grids)}")

그리드1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914]
그리드2: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926]
그리드3: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938]
그리드4: [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950]
그리드5: [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962]
그리드6: [61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974]
그리드7: [73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984]
그리드8: [4593, 4594, 4595, 4596, 4597, 4598, 4599, 4600, 4601, 4602, 4603, 4604, 4675, 4676, 4677, 4678, 4679, 4680, 4681, 4682, 4683, 4684, 4685, 4686, 4757, 4758, 4759, 4760, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4839, 4840, 4841, 4842, 4843, 4844, 4845, 4846, 4847, 4848, 4849, 4850, 4921, 4922, 4923, 4924, 4925, 4926, 4927, 4928, 4929, 4930, 4931, 4932, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, 5013, 5014, 5085, 5086, 5087, 5088, 5089, 5090, 5091, 5092, 5093, 5094, 5095, 5096, 5167, 5168, 5169, 5170, 5171, 5172, 5173, 5174, 5175, 5176, 5177, 5178, 5249, 5250, 5251, 5252, 5253, 5254, 5255, 5256, 5257, 5258, 5259, 5260, 5331, 5332, 5333, 5334, 5335, 5336, 5337, 5338, 5339, 5340, 5341, 5342, 5413, 5414, 5415, 5416, 5417, 5418, 5419, 5420, 5421, 5422, 5423, 5424, 5495, 5496, 5497, 5498, 5499, 5500, 5501, 5502, 5503, 5504, 5505, 5506]
그리드9: [4605, 4606, 4607, 4608, 4609, 4610, 4611, 4612, 4613, 4614, 4615, 4616, 4687, 4688, 4689, 4690, 4691, 4692, 4693, 4694, 4695, 4696, 4697, 4698, 4769, 4770, 4771, 4772, 4773, 4774, 4775, 4776, 4777, 4778, 4779, 4780, 4851, 4852, 4853, 4854, 4855, 4856, 4857, 4858, 4859, 4860, 4861, 4862, 4933, 4934, 4935, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 5015, 5016, 5017, 5018, 5019, 5020, 5021, 5022, 5023, 5024, 5025, 5026, 5097, 5098, 5099, 5100, 5101, 5102, 5103, 5104, 5105, 5106, 5107, 5108, 5179, 5180, 5181, 5182, 5183, 5184, 5185, 5186, 5187, 5188, 5189, 5190, 5261, 5262, 5263, 5264, 5265, 5266, 5267, 5268, 5269, 5270, 5271, 5272, 5343, 5344, 5345, 5346, 5347, 5348, 5349, 5350, 5351, 5352, 5353, 5354, 5425, 5426, 5427, 5428, 5429, 5430, 5431, 5432, 5433, 5434, 5435, 5436, 5507, 5508, 5509, 5510, 5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518]
그리드10: [4617, 4618, 4619, 4620, 4621, 4622, 4623, 4624, 4625, 4626, 4627, 4628, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709, 4710, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4789, 4790, 4791, 4792, 4863, 4864, 4865, 4866, 4867, 4868, 4869, 4870, 4871, 4872, 4873, 4874, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 5027, 5028, 5029, 5030, 5031, 5032, 5033, 5034, 5035, 5036, 5037, 5038, 5109, 5110, 5111, 5112, 5113, 5114, 5115, 5116, 5117, 5118, 5119, 5120, 5191, 5192, 5193, 5194, 5195, 5196, 5197, 5198, 5199, 5200, 5201, 5202, 5273, 5274, 5275, 5276, 5277, 5278, 5279, 5280, 5281, 5282, 5283, 5284, 5355, 5356, 5357, 5358, 5359, 5360, 5361, 5362, 5363, 5364, 5365, 5366, 5437, 5438, 5439, 5440, 5441, 5442, 5443, 5444, 5445, 5446, 5447, 5448, 5519, 5520, 5521, 5522, 5523, 5524, 5525, 5526, 5527, 5528, 5529, 5530]
그리드11: [4629, 4630, 4631, 4632, 4633, 4634, 4635, 4636, 4637, 4638, 4639, 4640, 4711, 4712, 4713, 4714, 4715, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4793, 4794, 4795, 4796, 4797, 4798, 4799, 4800, 4801, 4802, 4803, 4804, 4875, 4876, 4877, 4878, 4879, 4880, 4881, 4882, 4883, 4884, 4885, 4886, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 5039, 5040, 5041, 5042, 5043, 5044, 5045, 5046, 5047, 5048, 5049, 5050, 5121, 5122, 5123, 5124, 5125, 5126, 5127, 5128, 5129, 5130, 5131, 5132, 5203, 5204, 5205, 5206, 5207, 5208, 5209, 5210, 5211, 5212, 5213, 5214, 5285, 5286, 5287, 5288, 5289, 5290, 5291, 5292, 5293, 5294, 5295, 5296, 5367, 5368, 5369, 5370, 5371, 5372, 5373, 5374, 5375, 5376, 5377, 5378, 5449, 5450, 5451, 5452, 5453, 5454, 5455, 5456, 5457, 5458, 5459, 5460, 5531, 5532, 5533, 5534, 5535, 5536, 5537, 5538, 5539, 5540, 5541, 5542]
그리드12: [4641, 4642, 4643, 4644, 4645, 4646, 4647, 4648, 4649, 4650, 4651, 4652, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4732, 4733, 4734, 4805, 4806, 4807, 4808, 4809, 4810, 4811, 4812, 4813, 4814, 4815, 4816, 4887, 4888, 4889, 4890, 4891, 4892, 4893, 4894, 4895, 4896, 4897, 4898, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059, 5060, 5061, 5062, 5133, 5134, 5135, 5136, 5137, 5138, 5139, 5140, 5141, 5142, 5143, 5144, 5215, 5216, 5217, 5218, 5219, 5220, 5221, 5222, 5223, 5224, 5225, 5226, 5297, 5298, 5299, 5300, 5301, 5302, 5303, 5304, 5305, 5306, 5307, 5308, 5379, 5380, 5381, 5382, 5383, 5384, 5385, 5386, 5387, 5388, 5389, 5390, 5461, 5462, 5463, 5464, 5465, 5466, 5467, 5468, 5469, 5470, 5471, 5472, 5543, 5544, 5545, 5546, 5547, 5548, 5549, 5550, 5551, 5552, 5553, 5554]
그리드13: [4653, 4654, 4655, 4656, 4657, 4658, 4659, 4660, 4661, 4662, 4663, 4664, 4735, 4736, 4737, 4738, 4739, 4740, 4741, 4742, 4743, 4744, 4745, 4746, 4817, 4818, 4819, 4820, 4821, 4822, 4823, 4824, 4825, 4826, 4827, 4828, 4899, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 5063, 5064, 5065, 5066, 5067, 5068, 5069, 5070, 5071, 5072, 5073, 5074, 5145, 5146, 5147, 5148, 5149, 5150, 5151, 5152, 5153, 5154, 5155, 5156, 5227, 5228, 5229, 5230, 5231, 5232, 5233, 5234, 5235, 5236, 5237, 5238, 5309, 5310, 5311, 5312, 5313, 5314, 5315, 5316, 5317, 5318, 5319, 5320, 5391, 5392, 5393, 5394, 5395, 5396, 5397, 5398, 5399, 5400, 5401, 5402, 5473, 5474, 5475, 5476, 5477, 5478, 5479, 5480, 5481, 5482, 5483, 5484, 5555, 5556, 5557, 5558, 5559, 5560, 5561, 5562, 5563, 5564, 5565, 5566]
그리드14: [4665, 4666, 4667, 4668, 4669, 4670, 4671, 4672, 4673, 4674, 4747, 4748, 4749, 4750, 4751, 4752, 4753, 4754, 4755, 4756, 4829, 4830, 4831, 4832, 4833, 4834, 4835, 4836, 4837, 4838, 4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920, 4993, 4994, 4995, 4996, 4997, 4998, 4999, 5000, 5001, 5002, 5075, 5076, 5077, 5078, 5079, 5080, 5081, 5082, 5083, 5084, 5157, 5158, 5159, 5160, 5161, 5162, 5163, 5164, 5165, 5166, 5239, 5240, 5241, 5242, 5243, 5244, 5245, 5246, 5247, 5248, 5321, 5322, 5323, 5324, 5325, 5326, 5327, 5328, 5329, 5330, 5403, 5404, 5405, 5406, 5407, 5408, 5409, 5410, 5411, 5412, 5485, 5486, 5487, 5488, 5489, 5490, 5491, 5492, 5493, 5494, 5567, 5568, 5569, 5570, 5571, 5572, 5573, 5574, 5575, 5576]
그리드15: [985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898]
그리드16: [1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882]
그리드17: [2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3281, 3282, 3283, 3284, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456, 3527, 3528, 3529, 3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537, 3538, 3609, 3610, 3611, 3612, 3613, 3614, 3615, 3616, 3617, 3618, 3619, 3620, 3691, 3692, 3693, 3694, 3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3773, 3774, 3775, 3776, 3777, 3778, 3779, 3780, 3781, 3782, 3783, 3784, 3855, 3856, 3857, 3858, 3859, 3860, 3861, 3862, 3863, 3864, 3865, 3866]
그리드18: [3937, 3938, 3939, 3940, 3941, 3942, 3943, 3944, 3945, 3946, 3947, 3948, 4019, 4020, 4021, 4022, 4023, 4024, 4025, 4026, 4027, 4028, 4029, 4030, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108, 4109, 4110, 4111, 4112, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 4265, 4266, 4267, 4268, 4269, 4270, 4271, 4272, 4273, 4274, 4275, 4276, 4347, 4348, 4349, 4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4438, 4439, 4440, 4511, 4512, 4513, 4514, 4515, 4516, 4517, 4518, 4519, 4520, 4521, 4522, 4593, 4594, 4595, 4596, 4597, 4598, 4599, 4600, 4601, 4602, 4603, 4604, 4675, 4676, 4677, 4678, 4679, 4680, 4681, 4682, 4683, 4684, 4685, 4686, 4757, 4758, 4759, 4760, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4839, 4840, 4841, 4842, 4843, 4844, 4845, 4846, 4847, 4848, 4849, 4850]
그리드19: [1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968]
그리드20: [2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952]
그리드21: [3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278, 3279, 3280, 3351, 3352, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 3361, 3362, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3515, 3516, 3517, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3526, 3597, 3598, 3599, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3679, 3680, 3681, 3682, 3683, 3684, 3685, 3686, 3687, 3688, 3689, 3690, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3843, 3844, 3845, 3846, 3847, 3848, 3849, 3850, 3851, 3852, 3853, 3854, 3925, 3926, 3927, 3928, 3929, 3930, 3931, 3932, 3933, 3934, 3935, 3936]
그리드22: [4007, 4008, 4009, 4010, 4011, 4012, 4013, 4014, 4015, 4016, 4017, 4018, 4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098, 4099, 4100, 4171, 4172, 4173, 4174, 4175, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4253, 4254, 4255, 4256, 4257, 4258, 4259, 4260, 4261, 4262, 4263, 4264, 4335, 4336, 4337, 4338, 4339, 4340, 4341, 4342, 4343, 4344, 4345, 4346, 4417, 4418, 4419, 4420, 4421, 4422, 4423, 4424, 4425, 4426, 4427, 4428, 4499, 4500, 4501, 4502, 4503, 4504, 4505, 4506, 4507, 4508, 4509, 4510, 4581, 4582, 4583, 4584, 4585, 4586, 4587, 4588, 4589, 4590, 4591, 4592, 4663, 4664, 4665, 4666, 4667, 4668, 4669, 4670, 4671, 4672, 4673, 4674, 4745, 4746, 4747, 4748, 4749, 4750, 4751, 4752, 4753, 4754, 4755, 4756, 4827, 4828, 4829, 4830, 4831, 4832, 4833, 4834, 4835, 4836, 4837, 4838, 4909, 4910, 4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920]
총 그리드 수: 22

In [ ]:
import pandas as pd

# CSV 파일 로드
csv_file = "/content/final_with_d_score.csv"  # 파일 경로 지정
df = pd.read_csv(csv_file)

# 그리드 인덱스 매칭을 위한 딕셔너리 생성
grid_indices = {}

# 모든 그리드를 순회하며 grid_indices에 매핑
for idx, grid in enumerate(grids, start=1):
    for num in grid:
        grid_indices[num] = idx

# `image_name`이 숫자인 경우 정수형 변환 (필요 시)
df['image_name'] = df['image_name'].astype(int)

# `image_name`과 `grid_index` 매칭
df['grid_index'] = df['image_name'].map(grid_indices)

# 그리드별 데이터 분할 및 저장
for idx in df['grid_index'].dropna().unique():
    df_filtered = df[df['grid_index'] == idx]
    df_filtered.to_csv(f"merged_grid_{int(idx)}.csv", index=False)

# 전체 CSV 저장 (grid_index 포함)
df.to_csv("merged_with_grid_index.csv", index=False)

print("그리드 인덱스를 포함한 CSV 파일 생성 완료.")

그리드 인덱스를 포함한 CSV 파일 생성 완료.

In [ ]:
# prompt: merged_grid로 시작하는 파일 모두 데이터 개수 검사

import pandas as pd
import glob

# Find all files starting with "merged_grid"
merged_grid_files = glob.glob("merged_grid_*.csv")

for file in merged_grid_files:
    try:
        df = pd.read_csv(file)
        num_rows = len(df)
        print(f"File: {file}, Number of rows: {num_rows}")
    except FileNotFoundError:
        print(f"File not found: {file}")
    except pd.errors.EmptyDataError:
        print(f"File is empty: {file}")
    except Exception as e:
        print(f"Error processing file {file}: {e}")

File: merged_grid_21.csv, Number of rows: 2321
File: merged_grid_4.csv, Number of rows: 12
File: merged_grid_20.csv, Number of rows: 2264
File: merged_grid_6.csv, Number of rows: 402
File: merged_grid_22.csv, Number of rows: 1633
File: merged_grid_5.csv, Number of rows: 735
File: merged_grid_1.csv, Number of rows: 7801
File: merged_grid_16.csv, Number of rows: 615
File: merged_grid_15.csv, Number of rows: 1726
File: merged_grid_8.csv, Number of rows: 3656
File: merged_grid_12.csv, Number of rows: 233
File: merged_grid_17.csv, Number of rows: 4924
File: merged_grid_14.csv, Number of rows: 1768
File: merged_grid_2.csv, Number of rows: 4842
File: merged_grid_19.csv, Number of rows: 1355
File: merged_grid_9.csv, Number of rows: 1545
File: merged_grid_3.csv, Number of rows: 954
File: merged_grid_13.csv, Number of rows: 3991
File: merged_grid_11.csv, Number of rows: 1968
File: merged_grid_10.csv, Number of rows: 3167
File: merged_grid_18.csv, Number of rows: 5463

In [ ]:
# prompt: merged_grid로 시작하는 csv파일 모두 한데 모아서 zip

import zipfile

def zip_files(file_pattern, zip_filename):
  """Zips all files matching a given pattern into a single zip file."""
  with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for file in glob.glob(file_pattern):
      zipf.write(file)
  print(f"Files matching '{file_pattern}' zipped into '{zip_filename}'")

# Example usage: Zip all CSV files starting with "merged_grid"
zip_files("merged_grid_*.csv", "merged_grid_files.zip")

Files matching 'merged_grid_*.csv' zipped into 'merged_grid_files.zip'